### ISSUE TITLE
QoL suggestion

### ISSUE THREAD

**Issue by m0rtus59** [blepping/comfyui_jankhidiffusion#10]
Why not have the RAUNetSimple node pick the res_mode value based on the size of the latent image? Or at least based on the width/height input values.

**Comment by blepping** [comment]
> Why not have the RAUNetSimple node pick the res_mode value based on the size of the latent image? 

thanks for the suggestion!

i'll give this idea some more thought, but i _probably_ won't end up implementing it. one issue is that it would be relatively complicated because stuff like the latent size is only known after one of the patches gets called, so building the configuration would need to get refactored to only occur after that point.

probably the biggest reason though is because i see those settings as mostly just a suggestion - it's not _guaranteed_ that choosing "ultra" would be the best for very high res or whatever. there are only three possible settings, a user can just try them all to find what works best with their current workflow parameters in the worst case. that's already a very reduced set of options compared to the advanced node.

**Comment by blepping** [comment]
going to close this for now since i don't think i'll be taking that approach. there are some other QoL improvements coming soon though.
