### ISSUE TITLE
Confetti problem in SDXL

### ISSUE THREAD

**Issue by tudal** [blepping/comfyui_jankhidiffusion#4]
Ok so first of all this is real game changer, works insanely well!

Only problem I have is when I run it in SDXL with settings from example workflow. There's a lot of "confetti" on pictures (noise). Especially with dpmpp_2m at low steps. 3m and high steps is okayish, but its still visible. So I started tweaking the numbers randomly and those settings seems to do the job (0 confetti):

![image](https://github.com/blepping/comfyui_jankhidiffusion/assets/799063/2e6d4012-b46d-4a48-a01a-5d27af89ef57)

Not really issue ;) can be closed

**Comment by blepping** [comment]
you've actually just set the ApplyRAUNet node to not do anything. :) ca_start_time is 1.0 so it'll never activate. input block 6 for SDXL isn't a downsampler block and output block 3 isn't an upsampler block so that part also never has an effect.

if you're getting good results with those settings you basically just don't need the RAUNet stuff at all. what resolution are you trying to generate at?

**Comment by kubilaykilinc** [comment]
![image](https://github.com/blepping/comfyui_jankhidiffusion/assets/18080130/a73c3cd6-9c4d-4f9b-8e2e-dbfdec593614)

https://github.com/blepping/comfyui_jankhidiffusion/blob/main/assets/sdxl_workflow.png

I applied the above settings to your example SDXL workflow. It was okay. Thanks. This works.

**Comment by kubilaykilinc** [comment]
![image](https://github.com/blepping/comfyui_jankhidiffusion/assets/18080130/e64310f0-a19e-414f-9635-70b486c89941)
It works fine without any problems. The balloons disappeared. This problem only occurs on faces. This also happens on the other Hidiffusion custom node. I think it's related to the chosen resolution. Someone on Reddit wrote that there is no problem when applying the Standard SDXL dimensions by multiplying them by 1.5. I will try.

**Comment by kubilaykilinc** [comment]
This is 1.5 multiplier 1024x1024 pixel - (1536 x 1536). Working fine anatomy. I will examine different resoulitions.
![image](https://github.com/blepping/comfyui_jankhidiffusion/assets/18080130/673ac574-e4c7-455b-9b23-00397fadf538)

**Comment by blepping** [comment]
@kubilaykilinc 

> I applied the above settings to your example SDXL workflow. It was okay. Thanks. This works.

i'm confused as to why it works. you're downscaling but never upscaling because output 3 isn't an upsample block - so that part will have no effect at all. for SDXL, only targetting input 3 or 6, only targetting output 5 or 2 will have an effect. the patch can only apply to the correct block type, so if you try to use an input block that isn't actually a downscale block or an output block that isn't actually an upscale block then the handler will just never activate.

maybe the tensors broadcast or something, i'm not sure.

**Comment by blepping** [comment]
i'm going to close this now. any of the participants: please feel free to open another issue if you still have unresolved problems/questions.

**Comment by patientx** [comment]
> This is 1.5 multiplier 1024x1024 pixel - (1536 x 1536). Working fine anatomy. I will examine different resoulitions. ![image](https://private-user-images.githubusercontent.com/18080130/327955374-673ac574-e4c7-455b-9b23-00397fadf538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Mzg4MDksIm5iZiI6MTcxOTQzODUwOSwicGF0aCI6Ii8xODA4MDEzMC8zMjc5NTUzNzQtNjczYWM1NzQtZTRjNy00NTViLTliMjMtMDAzOTdmYWRmNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIxNDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOGU1NWFiMTY4ODBjMzJiYzk2YzRlOWNiYThlNDg1YmI0YTY4ZTBmYjI0NDdiNDA2NzM1ZDE0NTFkZTU4NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBtydTxqJstL7YVoC05AJi3Oi1ooWtcqHhZUbo1ntC0)

no matter what I try I can't get decent generation besides the sample workflow, can you share some workflow you use for sdxl with hidiffusion ? (selam!)
