### ISSUE TITLE
support Ella？

### ISSUE THREAD

**Issue by DENG-XC** [blepping/comfyui_jankhidiffusion#6]
Hi, this is a new amazing technic, thank you for your hard work to implement HiDiffusion in ComfyUI!!!
I am wonder that it is possible to use this technic with ella? (forgive about this dumb question, I am a code idiot)
https://github.com/TencentQQGYLab/ComfyUI-ELLA

**Comment by blepping** [comment]
> I am wonder that it is possible to use this technic with ella?

yes, it actually works really well! i've often used ELLA with jankhidiffusion with good results.

did you already try it and experience issues?

**Comment by DENG-XC** [comment]
> > I am wonder that it is possible to use this technic with ella?
> 
> yes, it actually works really well! i've often used ELLA with jankhidiffusion with good results.
> 
> did you already try it and experience issues?

I haven't use it with Ella, I am testing with parameter, trying to understand this node

**Comment by Omarsmsm** [comment]
i tried with Hypertile, works fine. Changes the result but doesnt seem to ruin it

**Comment by blepping** [comment]
> i tried with Hypertile, works fine. Changes the result but doesnt seem to ruin it

i guess it does work sometimes, but it's pretty sensitive to the resolution and depth you set in hypertile. also didn't really seem like it helped much with performance in my testing. it may just be (partially) overriding the MSW-MSA attention patch.

**Comment by blepping** [comment]
i'm going to close this since the question was answered. feel free to open another issue if you run into problems.

**Comment by DENG-XC** [comment]
> i see. well, it should work fine with:
> 
> 1. ELLA
> 2. SAG/PAG (self-attention/perturbed attention guidance)
> 3. FreeU and FreeU v2
> 4. CFG changes like CFG rescale and dynamic CFG
> 
> probably doesn't work with Deep Cache, HyperTile. can't remember if i tested with T-GATE. ToDo/ToME not sure about either, but they are supposedly similar to the attention change so you probably wouldn't want to use both.

I make a simple compare between HiDiffusion and SD1.5 output directly. would you like to take a look?
here is the setting parameter.

ApplyMSWMSAAttention
In/Mid/Out blocks: [1,2 /  / 9,10,11]
Time_mode: percent
Start_time/End_time: 0 / 1.0

ApplyRAUNet
In/Out blocks [3 / 8]
Time_mode: percent
Start/End percent: 0.0 / 0.6
Upscale_mode: bicubic
CA Start_time/End_time: 0.0/0.35
CA in/out blocks: [1 / 11]
CA upscale_mode: bicubic

Model: RealisticVision_V6.0
Steps: 20
CFG: 7.0
Sampler: dpmpp_sde
Schedule: karras

![对比图](https://github.com/blepping/comfyui_jankhidiffusion/assets/153186602/865f3d63-a823-4569-a56b-7d083cd308cf)

In some cases, use HiDiffusion get worst result. In this comparison image, HiDiffusion seem like start working in resolution 1152*1152, and output image getting better and better in higher resolution (but images still get some weird effect). For SD1.5, images works well under resolution 1408*1408, and collapse in resolution 1536*1536 and higher resolution.

**Comment by blepping** [comment]
@DENG-XC 

> I make a simple compare between HiDiffusion and SD1.5 output directly. would you like to take a look? here is the setting parameter.

appreciate that you took the time!

for SD, there's almost never a one size fits all set of parameters - you usually get the best results tuning stuff for a specific generation. i'm not surprised that hidiffusion results are worse when you're using a resolution close to what the model supports already. the RAUNet stuff is only to help the model deal with resolutions that are too high for it to handle normally.

also when the CA part is enabled you are doing a double downscale. this can be necessary with high resolutions but for something like 1152x1152 it's probably too much. one thing that might help (if you still want/need the RAUNet effect) would be to disable that part by setting `ca_start_time` to 1.0 (assuming you are in percent time mode) - that way it will never activate.

it might also help tweaking which blocks you are targetting. for the main RAUNet blocks on sd15 i don't think anything typically works better than the default 3/8, however for the CA scaling part instead of 1/11 you could try 2/10 or 4/8.

sometimes having MSW-MSA attention enabled early can have a strong effect on the generation or composition (in the worst case everything turns into squares). it can help to set it to kick in later, like `start_time` 0.3 or something like that. the downscaling effects from RAUNet also accelerate generation so the performance boost from the attention patch isn't as necessary at that point anyway.
